name: nestiq
description: A comprehensive student housing platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  firebase_messaging: ^14.6.1
  provider: ^6.0.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.6
  intl: ^0.18.1
  image_picker: ^0.8.7+5
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  firebase_database: ^10.5.7
  flutter_local_notifications: ^18.0.1
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.9.0
  another_carousel_pro: ^1.0.2
  custom_info_window: ^1.0.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

